on: [push, pull_request]

name: CI

jobs:
  build:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        racket-version: [ '7.9' ]
        racket-variant: [ 'CS', 'BC' ]

    name: Racket ${{ matrix.racket-version }} [${{ matrix.racket-variant }}]

    steps:
      - uses: actions/checkout@master

      - name: Setup Racket
        uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: minimal
          packages: 'compiler-lib'
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.racket/download-cache
          key: "${{ runner.os }}"

      - run: raco pkg install --auto --batch --no-docs
        working-directory: ./data-test
      - run: raco test tests/data/heap2.rkt
        working-directory: ./data-test
